- .github/workflows/regression_tests.yml
- :exclamation: Breaking Change
Add any summary information of what is in the change. **Remove this line if you have nothing to add.**
**Check who should review this. Remove this line once this has been done**
:information_source: This section is to be filled in by the **reviewer**.
> AEA-3563: named regression_tests.yml

- README.md
- :exclamation: Breaking Change
Add any summary information of what is in the change. **Remove this line if you have nothing to add.**
**Check who should review this. Remove this line once this has been done**
:information_source: This section is to be filled in by the **reviewer**.
> AEA-3563: Fixed readme link for badge

- .pre-commit-config.yaml
- .tool-versions
- pyproject.toml
Dependabot doesn't currently support python 3.12 so downgrading to the latest supprted version which is 3.11
:information_source: This section is to be filled in by the **reviewer**.
> downgraded from python 3.12 to python 3.11 to satisfy dependabot

- .github/workflows/auto-merge-dependabot.yml
- use github app to auto approve dependabot pull requests
**Check who should review this. Remove this line once this has been done**
:information_source: This section is to be filled in by the **reviewer**.
> use app for dependabot automerge

- .github/workflows/regression_tests.yml
- .pre-commit-config.yaml
- .tool-versions
- Makefile
- features/environment.py
- use separately named environment for pull requests
> use seperate environment for pull requests

- .github/workflows/regression_tests.yml
- make product optional in run tests workflow
> default product in workflow

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .tool-versions
- README.md
- features/environment.py
- features/eps_fhir/cancel_prescription.feature
- features/eps_fhir/create_prescription.feature
- features/steps/api_steps.py
- methods/eps_fhir/api_methods.py
- methods/shared/api.py
- utils/signing.py
> New: [AEA-3869] - Cancel single prescription

- features/environment.py
- features/eps_fhir/acute_prescriptions.feature
- features/eps_fhir/cancel_prescription.feature
- features/eps_fhir/create_prescriptions.feature
- features/eps_fhir/ping.feature
- features/eps_fhir/return_prescriptions.feature
- features/steps/api_steps.py
- methods/eps_fhir/api_methods.py
- methods/eps_fhir/api_request_body_generators.py
- methods/shared/api.py
- methods/shared/common.py
- package-lock.json
- utils/signing.py
Added a test that tests the returning of an acute prescription
Pull requests should be named using the following format:
```text
Tag: [AEA-NNNN] - Short description
```
Tag can be one of:
- `Fix` - for a bug fix. (Patch release)
- `Update` - either for a backwards-compatible enhancement or for a rule change that adds reported problems. (Patch release)
- `New` - implemented a new feature. (Minor release)
- `Breaking` - for a backwards-incompatible enhancement or feature. (Major release)
- `Docs` - changes to documentation only. (Patch release)
- `Build` - changes to build process only. (No release)
- `Upgrade` - for a dependency upgrade. (Patch release)
- `Chore` - for refactoring, adding tests, etc. (anything that isn't user-facing). (Patch release)
If the current …
> New: [AEA-3866] - return an acute prescription

- Makefile
- README.md
- features/eps_fhir/cancel_prescription.feature
- features/steps/api_steps.py
Switched the assertion for cancelling prescriptions to be less generic
> Fix: [AEA-4174] - medication request status history not used in automation tests

- .github/workflows/regression_tests.yml
- get_token.py
- package-lock.json
- pyproject.toml
- scripts/send_test_results.py
- :exclamation: Breaking Change
Instead of opening a new branch an uploading the test results to be processed. The action will now only upload the artifact and then send an API request to the test reports to begin the process of processing and uploading the results
Pull requests should be named using the following format:
```text
Tag: [AEA-NNNN] - Short description
```
Tag can be one of:
- `Fix` - for a bug fix. (Patch release)
- `Update` - either for a backwards-compatible enhancement or for a rule change that adds reported problems. (Patch release)
- `New` - implemented a new feature. (Minor release)
- `Breaking` - for a backwards-incompatible enhancement or feature. (Major …
> Breaking: [AEA-3819] - Generate reports in a cleaner way

- get_token.py
Updates get_token.py to optionally accept env and user as command line arguments
> Chore: [AEA-0000] - Adds optional get_token arg parsing

- features/environment.py
This fixes a bug where an empty report will be generated after successfully running 0 tests due to tags that are not applied to any scenario or feature
A count of scenarios with the supplied tags are returned. a check has been applied to the before_all and after_all hooks to verify this is not 0.
If it is, we throw an assertion error (causing a failure in CI) and we delete the allure-results folder so that the reports repo will not attempt to process the empty results
> Fix: [AEA-3875] - Broken reports generated after using unrecognised tags

- features/steps/pfp_api_steps.py
- messages/eps_fhir/prescription.py
Fix for bug when testing in Sandbox
Sandbox is static, so there's no prescriptions to make. inserted static values instead.
> Fix: [AEA-4323] - PfP Automation Authentication Errors

- features/environment.py
- features/eps_fhir/create_prescriptions.feature
Added logic to check product under test before appending pr tag
> Fix: [AEA-4324] - PFP Regression tests failing on Pull Requests

- messages/eps_fhir/signed_prescription.py
- methods/api/eps_api_methods.py
- utils/signing.py
Changed SHA signing hash from SHA1 to SHA256
> New: [AEA-4346] - Toggle EPS processing to SHA-256

- features/environment.py
Quick fix to ensure pr-xxxx beings with "pr-" before considering this as a pr
> Fix: [AEA-0000] - Integrating PSU CI

- features/environment.py
Quick fix to prevent non pr version numbers appearing as PRs in the reports that are later generated
> Fix: [AEA-4321] - integrating psu ci

- .tool-versions
- features/eps_fhir/create_prescriptions.feature
- features/psu/send_status_update.feature
- features/steps/eps_api_steps.py
- features/steps/psu_api_steps.py
- messages/psu/prescription_status_update.py
- methods/api/common_api_methods.py
> New: [AEA-4336] - Create a prescription in PSU and check updates in PfP

- features/steps/common_steps.py
- features/steps/eps_api_steps.py
- features/steps/psu_api_steps.py
> Fix: [AEA-0000] - Skip steps if sandbox

- .github/workflows/regression_tests.yml
only trigger report building if there are test failures
> New: [AEA-4607] - Amendments to test report history

- features/cpts_ui/home_page.feature
- features/steps/cpts_ui_home_page_steps.py
- pages/home_page.py
> Chore: [AEA-4515] - Set up footer

- Makefile
> Chore: [AEA-0000] - added git-secrets-docker-setup to make file

- .github/workflows/regression_tests.yml
- scripts/set_secrets.sh
Feature under test: Enable prescribing systems to toggle to SHA-256 unilaterally
> New: [AEA-4587] - Added option for second run against SHA1 app

- .gitignore
- features/cpts_ui/select_your_role.feature
- features/environment.py
- features/steps/__init__.py
- features/steps/cpts_ui/select_your_role_steps.py
- pages/select_your_role.py
Brings my regression tests over to Kris' branch
> Merge in roles with access

- .github/workflows/regression_tests.yml
- .gitignore
- Makefile
- features/cpts_ui/home.feature
- features/cpts_ui/search_for_a_prescription.feature
- features/cpts_ui/select_your_role.feature
- features/environment.py
- features/steps/__init__.py
- features/steps/cpts_ui/select_your_role_steps.py
- package-lock.json
- package.json
- pages/select_your_role.py
- scripts/set_secrets.sh
This is a single PR for the `Roles with access` and `Roles without access` features, since there is some degree of code overlap.
Old PR for Roles With Access: #199
That will be closed, and only this PR will need review.
> New: [AEA-4653] - [AEA-4651] - Combined PR for Select your Role page features

- features/cpts_ui/select_your_role.feature
- features/environment.py
- features/steps/cpts_ui/select_your_role_steps.py
- pages/select_your_role.py
🎫 [AEA-4658](https://nhsd-jira.digital.nhs.uk/browse/AEA-4658) Select your role page header
Added tests for the Select Your Role page header.
> Chore: [AEA-4658] - Select your role page header

- .github/workflows/regression_tests.yml
> Fix: [AEA-0000] - Updated github action cache version to v4

- .devcontainer/devcontainer.json
- README.md
- features/cpts_ui/logout.feature
- features/cpts_ui/select_your_role.feature
- features/environment.py
- features/steps/cpts_ui/common_steps.py
- features/steps/cpts_ui/logout_steps.py
- features/steps/cpts_ui/search_for_a_prescription_steps.py
- features/steps/cpts_ui/select_your_role_steps.py
Uncomments the logout tests, and makes them compatible with the select your role tests.
Also makes localhost testing available.
> Update: [AEA-4809] - Re-enable logout tests, and some other minor things

- .github/workflows/auto-merge-dependabot.yml
- .github/workflows/pr-link.yml
- .github/workflows/pr_title_check.yml
- .github/workflows/regression_tests.yml
- .github/workflows/release.yml
> Fix: [AEA-0000] - pin ubuntu image to 22.04

- README.md
- features/cpts_ui/confirm_your_role.feature
- features/environment.py
- features/steps/__init__.py
- features/steps/cpts_ui/change_role_steps.py
- features/steps/cpts_ui/confirm_role_steps.py
- pages/confirm_role.py
As the title says. Adds regression tests for [PR 351](https://github.com/NHSDigital/eps-prescription-tracker-ui/pull/351)
> New: [AEA-4537] - Add regression tests for confirm role page

- features/cpts_ui/confirm_your_role.feature
- features/cpts_ui/logout.feature
- features/cpts_ui/search_for_a_prescription.feature
- features/steps/cpts_ui/select_your_role_steps.py
🎫 [AEA-4755](https://nhsd-jira.digital.nhs.uk/browse/AEA-4755) PUT /selectedRole
**PR** [https://github.com/NHSDigital/eps-prescription-tracker-ui/pull/334](https://github.com/NHSDigital/eps-prescription-tracker-ui/pull/334)
:sparkles: New Feature
🧪 Regression tests for a selectedRole lambda
> New: [AEA-4755] - PUT /selectedRole

- methods/shared/common.py
> Fix: [AEA-0000] - fix typo for product

- .devcontainer/Dockerfile
- .github/workflows/regression_tests.yml
- .github/workflows/release.yml
- pin asdf version in github action
- upgrade to latest asdf
> Fix: [AEA-0000] - pin asdf version

- features/psu/send_status_update.feature
- skip broken psu e2e test that does not work with pull requests
> Fix: [AEA-0000] - skip psu e2e test

- features/eps_fhir/cancel_prescriptions.feature
- features/eps_fhir/create_prescriptions.feature
- features/eps_fhir/metadata.feature
- features/eps_fhir/validator.feature
- skip sandbox tests that do not work
> Fix: [AEA-0000] - skip sandbox tests that do not work

- features/cpts_ui/prescription_list.feature
- features/steps/__init__.py
- features/steps/cpts_ui/home_steps.py
- features/steps/cpts_ui/login_steps.py
- features/steps/cpts_ui/prescription_list_steps.py
- pages/prescription_list_page.py
- pages/search_for_a_prescription.py
- :sparkles: New Feature - adds e2e tests for the Prescription List Page
> New: [AEA-4778] - Prescriptions list page

- features/environment.py
- features/steps/cpts_ui/rbac_banner.py
- capture screenshot on test failure
> Fix: [AEA-0000] - capture screenshot on test failure

- features/environment.py
- features/steps/cpts_ui/change_role_steps.py
- pages/change_role.py
- pages/footer.py
- pages/header.py
- pages/home.py
- pages/logout.py
- pages/page_not_found.py
- pages/prescription_list_page.py
- pages/rbac_banner.py
- pages/search_for_a_prescription.py
- pages/select_your_role.py
- pages/your_selected_role.py
- attach trace to allure for test failures
- use wait for load state on each page
> Fix: [AEA-0000] - Capture trace on failure

- .gitallowed
- features/cpts_ui/prescription_detail.feature
- features/cpts_ui/prescription_information_banner.feature
- features/steps/cpts_ui/prescription_details_steps.py
- features/steps/cpts_ui/prescription_information_banner.py
- pages/prescription_details.py
🎫 [AEA-4799](https://nhsd-jira.digital.nhs.uk/browse/AEA-4799) Prescribed and Dispensed Items
**PR** https://github.com/NHSDigital/eps-prescription-tracker-ui/pull/693
:sparkles: New Feature
🧪 Regression tests for the implementation of the Prescribed and Dispensed Items on the prescription-details page
> New: [AEA-4799] - Prescribed and Dispensed Items

- features/cpts_ui/patient_detail_banner.feature
- features/cpts_ui/search_for_a_prescription.feature
- features/steps/cpts_ui/search_for_a_prescription_steps.py
- pages/search_for_a_prescription.py
🎫 [AEA-4784](https://nhsd-jira.digital.nhs.uk/browse/AEA-4784) Search by NHS Number - CPTS UI
**PR** https://github.com/NHSDigital/eps-prescription-tracker-ui/pull/
:sparkles: New Feature
🧪 Added regression tests for the implementation of the Search by NHS Number - CPTS UI component.
> New: [AEA-4784] - Search by NHS Number - CPTS UI

- .github/workflows/release.yml
added steps to release.yml to output bdd steps and publish to gh pages
> New: [AEA-5261] - Publish a catalogue of the BDD used in the regression test pack

- .github/workflows/release.yml
Disable history expansion to prevent !DOCTYPE error
> Fix: [AEA-5261] - publish a catalogue of the bdd used

- Makefile
- README.md
* Updates to make commands to allow for easier installation, and re-installation
* Updates to the README.md
> New: [AEA-5346] - Documentation

- features/cpts_ui/basic_details_search_results.feature
- features/steps/__init__.py
- features/steps/cpts_ui/basic_details_search_results_steps.py
- package-lock.json
- pages/basic_details_search_results.py
- poetry.lock
**Adds test scenarios for the dummy data populated Basic Details Search results page**
This ticket is to implement the multiple results page path from the Basic Details Search functionality
> New: [AEA-4790] - multiple patients results for basic details search

- features/cpts_ui/search_for_a_prescription.feature
- features/cpts_ui/search_results_too_many.feature
- features/steps/__init__.py
- features/steps/cpts_ui/search_for_a_prescription_steps.py
- features/steps/cpts_ui/search_results_too_many_steps.py
- pages/search_for_a_prescription.py
- pages/search_results_too_many.py
🎫 [AEA-4785](https://nhsd-jira.digital.nhs.uk/browse/AEA-4785) Basic Details Search - CPTS UI
**PR** https://github.com/NHSDigital/eps-prescription-tracker-ui/pull/838
:sparkles: New Feature
🧪 Added regression tests for the implementation of the Basic Details Search feature.
> New: [AEA-4785] - Basic Details Search - CPTS UI

- features/cpts_ui/header.feature
- fix the tests where you see change role header
> Fix:[AEA-0000] - fix tests where you see change role

- features/cpts_ui/cookie.feature
- features/steps/__init__.py
- features/steps/cpts_ui/cookie_steps.py
Fixed tests broken by other merge
> New: [AEA-5182] - resolved broken tests

- features/cpts_ui/search_for_a_prescription.feature
> Fix: [AEA-5343] - skipped tests that rely on mock data for nhs number search

- features/steps/cpts_ui/login_steps.py
- runner.py
> Fix: [AEA-0000] - retry login

- features/cpts_ui/basic_details_search_results.feature
- features/cpts_ui/search_for_a_prescription.feature
- features/cpts_ui/search_results_too_many.feature
> Fix: [AEA-4754] - skipped tests that rely on mock data for patient search

- features/steps/cpts_ui/home_steps.py
- features/steps/cpts_ui/login_steps.py
> Fix: [AEA-0000] - change go to login step

- features/steps/cpts_api_steps.py
- methods/api/cpts_api_methods.py
- 
- Updates CPT API Not found test to use a valid format prescriptionID
- Swaps a couple of CPT API steps to use a common method
> New: [AEA-5565] - Update CPT Not Found test to use valid format prescription ID

- methods/shared/common.py
- no trailing slash in callback url
> Fix: [AEA-0000] - no trailing slash in callback url

- features/steps/cpts_ui/select_your_role_steps.py
- features/steps/cpts_ui/your_selected_role_steps.py
> Fix: [AEA-5613] - bug fix psu status not showing

- features/cpts_ui/select_your_role.feature
- features/steps/common_steps.py
- :exclamation: Breaking Change
Add any summary information of what is in the change. **Remove this line if you have nothing to add.**
Pull requests should be named using the following format:
```text
Tag: [AEA-NNNN] - Short description
```
Tag can be one of:
- `Fix` - for a bug fix. (Patch release)
- `Update` - either for a backwards-compatible enhancement or for a rule change that adds reported problems. (Patch release)
- `New` - implemented a new feature. (Minor release)
- `Breaking` - for a backwards-incompatible enhancement or feature. …
> Update: [AEA-5407] - Redirection Issues when no role selected

- features/steps/cpts_ui/logout_steps.py
Don't attempt to go back twice as we only redirect to logout once
> Fix: [AEA-0000] - Don't attempt to go back twice as we only redirect to logout once
